import moment from "moment";

export const dashboardFormConfig = [
  {
    id: 1,
    name: "Chart",
    formData: {
      chartHeader: "Amount By Stage",
      chartSubHeader: "Total Amount",
      chartAmount: "1195500",
      source: "",
      type: "",
      unit: "$",
      compare: "",
      size: "",
    },
  },
  {
    id: 2,
    name: "NumberData",
    formData: {
      numberHeader: "New Patient",
      numberAmount: "10",
      numberLastAmount: "220000",
      Source: "New Patient",
      Type: "",
      unit: "$",
      size: "",
    },
  },
  {
    id: 3,
    name: "Deals Revenue Forecast",
    formData: {
      Source: "",
      Type: "",
      revenueHeader: "Revenue ForeCast",
      totalGoal: "Company Goals",
      indiGoal: "Team Goals",
      goalHeader: "Febuary Goals",
      totalGoalAmt: "300000",
      indiGoalTitle1: "Cash Collected",
      indiGoalTitle2: "Paid Claims",
      indiGoalTitle3: "Pending Claims",
      indiGoal1Amt: "29000",
      indiGoal2Amt: "120060",
      indiGoal3Amt: "139100",
      indiGoal1TotalAmt: "150000",
      indiGoal2TotalAmt: "150000",
      indiGoal3TotalAmt: "150000",
      unit: "$",
      size: "",
    },
  },
  {
    id: 4,
    name: "Simple Data",
    formData: {
      simpleHeader: "Task Due",
      unit: "$",
      Source: "",
      Type: "",
      cardData: [
        {
          simpleCardTitle: "Web Development deal with jane",
          simpleCardImage: "/images/avatar/yellowdog.jpg",
          simpleStatus: "Contract Sent",
          simpleDate: "10 Jan 2021",
          clientName: "John Macoy",
          amount: "45000",
          unit: "$",
        },
        {
          simpleCardTitle: "Web Development deal with jane",
          simpleCardImage: "/images/avatar/yellowdog.jpg",
          simpleStatus: "Contract Sent",
          simpleDate: "10 Jan 2021",
          clientName: "John Macoy",
          amount: "45000",
          unit: "$",
        },
        {
          simpleCardTitle: "Web Development deal with jane",
          simpleCardImage: "/images/avatar/yellowdog.jpg",
          simpleStatus: "Contract Sent",
          simpleDate: "18 Dec 1998",
          clientName: "John Macoy",
          amount: "45000",
          unit: "$",
        },
      ],
    },
  },
  {
    id: 5,
    name: "Task ",
    formData: {
      Source: "",
      Type: "",
      taskAuthor: "Easthor Howard",
      taskTitle: "Prepare quote for Jerome Bell",
      taskPara:
        "She is interested in our new product line and wants our very best price. Please include a detailed breakdown of costs.",
      taskDate: moment(new Date()).format("DD MMM YYYY"),
    },
  },
  {
    id: 6,
    name: "Calendar ",
    unit: "$",
    Source: "",
    Type: "",
    formData: {
      calendarHeader: "Appointment Today",
      cardData: [
        {
          calendarItemHeader: "Yolanda Veru Nu",
          calendarDesc: " She interested in our new product line.",
          calendarTime: new Date(),
          therapyRoom: "Physical Therapy Room",
        },
        {
          calendarItemHeader: "Yolanda Veru Nu",
          calendarDesc: " She interested in our new product line.",
          therapyRoom: "Physical Therapy Room",
          calendarTime: new Date(),
        },
        {
          calendarItemHeader: "Yolanda Veru Nu",
          calendarDesc: " She interested in our new product line.",
          therapyRoom: "Physical Therapy Room",
          calendarTime: new Date(),
        },
      ],
    },
  },
  {
    id: 7,
    name: "Email",
    formData: {
      emailHeader: "Email Performance Report",
      Source: "",
      Type: "",
    },
  },
  {
    id: 8,
    name: "Gantt",
    formData: {
      ganttHeader: "Amount By Stage",
      Source: "",
      Type: "",
    },
  },
  {
    id: 9,
    name: "PipeLine Sales Chart",
    formData: {
      pipelineHeader: "Sales Pipeline",
      Source: "",
      Type: "",
      // pipelineAmtHeader:"1195500",
      pipelineDealsHeader: "",
      pipelineAmount: "1195500",
      pipelineDealsNumber: "89",
      unit: "$",
      size: "",
    },
  },
];
